[package]
name = "os_display"
version = "0.1.0"
authors = ["Jan Verbeek <jan.verbeek@posteo.nl>"]
license = "MIT"
readme = "README.md"
exclude = ["fuzz", "benches", ".gitignore"]
edition = "2018"

[dependencies]
unicode-width = "0.1.9"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false
